import test from "node:test";import assert from "node:assert/strict";
import {initialLayout,validLayout,moveLayout,project,unproject,classifyLayout} from "./layout";
import {initialState,transition,restore,type Action,type State} from "./model";
let n=0;const act=(s:State,action:Action)=>transition(s,{id:`layout-${++n}`,at:"2026-09-28T00:00:00Z",action});
test("default ground footprints are valid and projection round trips",()=>{const l=initialLayout();assert.equal(validLayout(l),true);for(const p of Object.values(l)){const q=project(p),r=unproject(q.x,q.y);assert.ok(Math.abs(p.u-r.u)<1e-9&&Math.abs(p.v-r.v)<1e-9);}});
test("floor placement allows asymmetry but rejects overlaps, walls and out of bounds",()=>{const l=initialLayout();assert.ok(moveLayout(l,"chair",{u:.45,v:.35}));assert.equal(moveLayout(l,"chair",l.sofa),null);assert.equal(moveLayout(l,"chair",{u:.45,v:-.5}),null);assert.equal(moveLayout(l,"sofa",{u:2,v:.5}),null);assert.equal(moveLayout(l,"chair",{u:NaN,v:.5}),null);assert.ok(moveLayout(l,"chair",{u:.5,v:.055}));assert.equal(moveLayout(l,"chair",{u:.5,v:0}),null);});
test("combined table and chair moves as one footprint",()=>{assert.ok(moveLayout(initialLayout(),"table-chair",{u:.45,v:.85}));assert.equal(moveLayout(initialLayout(),"table-chair",initialLayout().sofa),null);});
test("edits require arranging mode, invalid drop creates no event, undo and reset are reversible",()=>{let s=initialState();const move:Action={type:"layout-move",id:"chair",point:{u:.45,v:.35}};assert.equal(act(s,move),s);s=act(s,{type:"layout-start"});assert.equal(act(s,{type:"sit",seat:"chair",yes:true}),s);const initial=s.furniture.layout;assert.equal(act(s,{type:"layout-move",id:"chair",point:s.furniture.layout.sofa}),s);s=act(s,move);assert.notDeepEqual(s.furniture.layout,initial);assert.deepEqual(restore(JSON.stringify({version:1,events:s.events})),s);s=act(s,{type:"layout-undo"});assert.deepEqual(s.furniture.layout,initial);s=act(s,move);s=act(s,{type:"layout-reset"});assert.deepEqual(s.furniture.layout,initial);s=act(s,{type:"layout-undo"});assert.deepEqual(s.furniture.layout.chair,{u:.45,v:.35});});
test("confirmation snapshots layout; next movement invalidates old confirmation",()=>{let s=act(initialState(),{type:"layout-start"});s=act(s,{type:"layout-confirm"});assert.equal(s.furniture.editing,false);assert.deepEqual(s.furniture.confirmed,s.furniture.layout);assert.equal(s.furniture.classification?.reasonable,true);assert.equal(act(s,{type:"layout-confirm"}),s);s=act(s,{type:"layout-start"});s=act(s,{type:"layout-move",id:"chair",point:{u:.45,v:.35}});assert.equal(s.furniture.confirmed,null);s=act(s,{type:"layout-exit"});assert.equal(s.furniture.editing,false);assert.deepEqual(restore(JSON.stringify({version:1,events:s.events})),s);});
test("open placement classifier rejects invalid layouts and returns versioned prototype evidence",()=>{const l=initialLayout();assert.equal(classifyLayout({...l,chair:l.sofa}).reasonable,false);assert.equal(classifyLayout(l).ruleVersion,"l2-placement-v2");});

test("light overlap allowed, deep overlap rejected using smaller footprint",()=>{const l=initialLayout();const half=.31/2+.085/2;const light={u:l.sofa.u-half+.085*.19,v:l.sofa.v};const deep={...light,u:l.sofa.u-half+.085*.30};assert.ok(moveLayout(l,"chair",light));assert.equal(moveLayout(l,"chair",deep),null);});
test("one moved piece in open destination triggers both events; unchanged layout triggers neither",()=>{const l=initialLayout();assert.deepEqual(classifyLayout(l,l).events,[]);const moved=moveLayout(l,"chair",{u:.45,v:.35})!;const c=classifyLayout(moved,l);assert.equal(c.tidy,true);assert.equal(c.openPlacement,true);assert.deepEqual(c.movedIds,["chair"]);assert.deepEqual(c.events,["tidy","open-placement"]);assert.deepEqual(classifyLayout(moved,l,{tidy:true,openPlacement:true}).events,[]);});
test("crowded but reasonable placement is tidy without open-placement",()=>{const l=initialLayout();const p={u:l.sofa.u-(.31+.085)/2+.01,v:l.sofa.v};const moved=moveLayout(l,"chair",p)!;assert.ok(moved);const c=classifyLayout(moved,l);assert.equal(c.tidy,true);assert.equal(c.openPlacement,false);});
test("confirmation deduplicates derived events and undo restores no-change semantics",()=>{let s=act(initialState(),{type:"layout-start"});s=act(s,{type:"layout-move",id:"chair",point:{u:.45,v:.35}});s=act(s,{type:"layout-undo"});s=act(s,{type:"layout-confirm"});assert.deepEqual(s.furniture.classification?.events,[]);s=act(s,{type:"layout-start"});s=act(s,{type:"layout-move",id:"chair",point:{u:.45,v:.35}});s=act(s,{type:"layout-confirm"});assert.equal(s.furniture.triggered.openPlacement,true);s=act(s,{type:"layout-start"});s=act(s,{type:"layout-confirm"});assert.deepEqual(s.furniture.classification?.events,[]);assert.deepEqual(restore(JSON.stringify({version:1,events:s.events})),s);});
