import test from "node:test";
import assert from "node:assert/strict";
import {initialState,transition,restore,type Action,type State} from "./model";
import {SearchClock} from "./searchClock";
let n=0;const act=(s:State,action:Action)=>transition(s,{id:`search-${++n}`,at:"2026-09-28T00:00:00Z",action});
function bedroom(){let s=act(initialState(),{type:"arrive-table"});for(const key of ["key-1","key-2"] as const){s=act(s,{type:"select-key",key});s=act(s,{type:"try-door",key});}return act(s,{type:"explore",yes:true});}
test("search requires bedroom and explicit consent; refusal can be reconsidered",()=>{let s=initialState();assert.equal(act(s,{type:"search-choice",yes:true}),s);s=bedroom();assert.equal(act(s,{type:"find-earring"}),s);s=act(s,{type:"search-choice",yes:false});assert.equal(s.search.status,"declined");s=act(s,{type:"search-choice",yes:true});assert.equal(s.search.status,"searching");assert.equal(s.search.activeMs,0);assert.equal(act(s,{type:"search-choice",yes:true}),s);});
test("14999 and 15000 return short; only 15001 is long while searching",()=>{for(const activeMs of [14999,15000,15001]){let s=act(bedroom(),{type:"search-choice",yes:true});s=act(s,{type:"search-time",activeMs});assert.equal(s.search.long,activeMs>15000);s=act(s,{type:"return-hall"});assert.equal(s.search.status,"returned");assert.equal(s.search.long,activeMs>15000);assert.equal(act(s,{type:"search-time",activeMs:activeMs+1}),s);}});
test("found is terminal and survives replay; invalid time is rejected",()=>{let s=act(bedroom(),{type:"search-choice",yes:true});s=act(s,{type:"search-time",activeMs:500});for(const activeMs of [-1,499,500,NaN,Infinity,1.5])assert.equal(act(s,{type:"search-time",activeMs}),s);for(let i=0;i<3;i++)s=act(s,{type:"curtain-click"});assert.equal(s.search.status,"found");assert.equal(act(s,{type:"find-earring"}),s);assert.equal(act(s,{type:"search-choice",yes:true}),s);assert.deepEqual(restore(JSON.stringify({version:1,events:s.events})),s);});
test("return and revisit starts a new segment without losing previous events",()=>{let s=act(bedroom(),{type:"search-choice",yes:true});s=act(s,{type:"search-time",activeMs:15001});s=act(s,{type:"return-hall"});s=act(s,{type:"explore",yes:true});s=act(s,{type:"search-choice",yes:true});assert.equal(s.search.activeMs,0);assert.equal(s.search.long,false);assert.equal(s.events.filter(e=>e.action.type==="search-choice").length,2);});
test("active clock excludes paused and offline intervals and does not double resume",()=>{let now=0;const c=new SearchClock(()=>now);now=1000;assert.equal(c.read(),0);c.resume();now=3000;c.pause();now=90000;assert.equal(c.read(),2000);c.resume();c.resume();now=93000;assert.equal(c.read(),5000);c.pause();c.pause();now=120000;assert.equal(c.read(),5000);});

test("curtain reveals only on third unique click and keeps progress across return/replay",()=>{let s=bedroom();assert.equal(act(s,{type:"curtain-click"}),s);s=act(s,{type:"search-choice",yes:true});s=act(s,{type:"curtain-click"});assert.equal(s.search.status,"searching");s=act(s,{type:"curtain-click"});assert.equal(s.search.curtainClicks,2);assert.equal(s.search.status,"searching");s=restore(JSON.stringify({version:1,events:s.events}));s=act(s,{type:"return-hall"});s=act(s,{type:"explore",yes:true});s=act(s,{type:"search-choice",yes:true});assert.equal(s.search.curtainClicks,2);s=act(s,{type:"curtain-click"});assert.equal(s.search.status,"found");assert.equal(s.search.curtainClicks,3);assert.equal(act(s,{type:"curtain-click"}),s);assert.equal(act(s,{type:"find-earring"}),s);});
